var searchData=
[
  ['schemas_0',['Dynamic config schemas',['../de/d10/md_en_2schemas_2dynamic__configs.html',1,'']]],
  ['security_20changelog_1',['Security Changelog',['../db/dde/md_en_2userver_2security__changelog.html',1,'']]],
  ['security_20policy_2',['Security Policy',['../de/d1b/md__2data_2code_2userver_2SECURITY.html',1,'']]],
  ['server_3',['server',['../da/d16/md_en_2userver_2tutorial_2hello__service.html',1,'Writing your first HTTP server'],['../d4/d95/md_en_2userver_2tutorial_2config__service.html',1,'Writing your own configs server']]],
  ['server_20middlewares_4',['Http server middlewares',['../d6/dcc/md_en_2userver_2http__server__middlewares.html',1,'']]],
  ['server_20with_20metrics_20and_20spans_5',['TCP full-duplex server with metrics and Spans',['../db/db9/md_en_2userver_2tutorial_2tcp__full.html',1,'']]],
  ['server_20with_20static_20configs_20validation_6',['TCP half-duplex server with static configs validation',['../dc/d93/md_en_2userver_2tutorial_2tcp__service.html',1,'']]],
  ['service_7',['service',['../d6/daa/md_en_2userver_2tutorial_2grpc__service.html',1,'gRPC client and service'],['../d4/d1a/md_en_2userver_2memory__profile__running__service.html',1,'Memory profiling a production service'],['../d5/d81/md_en_2userver_2tutorial_2mongo__service.html',1,'MongoDB service'],['../d4/d31/md_en_2userver_2tutorial_2postgres__service.html',1,'PostgreSQL service'],['../d3/da2/md_en_2userver_2tutorial_2redis__service.html',1,'Redis service'],['../d7/d9e/md_en_2userver_2tutorial_2websocket__service.html',1,'Writing your WebSocket service']]],
  ['service_20statistics_20and_20metrics_20prometheus_20graphite_8',['Service Statistics and Metrics (Prometheus/Graphite/...)',['../d9/dac/md_en_2userver_2service__monitor.html',1,'']]],
  ['service_20tests_20testsuite_9',['Functional service tests (testsuite)',['../df/d07/md_en_2userver_2functional__testing.html',1,'']]],
  ['sets_10',['uPg: Working with result sets',['../db/db5/pg_process_results.html',1,'']]],
  ['signals_11',['Handling OS signals',['../df/d4e/md_en_2userver_2os__signals.html',1,'']]],
  ['spans_12',['TCP full-duplex server with metrics and Spans',['../db/db9/md_en_2userver_2tutorial_2tcp__full.html',1,'']]],
  ['specific_20configurations_13',['Deploy Environment Specific Configurations',['../d2/d58/md_en_2userver_2deploy__env.html',1,'']]],
  ['stability_20versioning_14',['API and ABI stability, versioning',['../db/d57/md_en_2userver_2development_2stability.html',1,'']]],
  ['static_20configs_20validation_15',['TCP half-duplex server with static configs validation',['../dc/d93/md_en_2userver_2tutorial_2tcp__service.html',1,'']]],
  ['statistics_20and_20metrics_20prometheus_20graphite_16',['Service Statistics and Metrics (Prometheus/Graphite/...)',['../d9/dac/md_en_2userver_2service__monitor.html',1,'']]],
  ['strong_20typedef_20idiom_17',['uPg: support for C++ &apos;strong typedef&apos; idiom',['../d3/ddf/pg_strong_typedef.html',1,'']]],
  ['support_18',['uPg timestamp support',['../df/d8a/pg_timestamp.html',1,'']]],
  ['support_20for_20c_20strong_20typedef_20idiom_19',['uPg: support for C++ &apos;strong typedef&apos; idiom',['../d3/ddf/pg_strong_typedef.html',1,'']]],
  ['supported_20data_20types_20',['uPg: Supported data types',['../d0/d89/pg_types.html',1,'']]],
  ['supported_20platforms_21',['Supported Platforms',['../d0/dd5/md_en_2userver_2supported__platforms.html',1,'']]],
  ['supported_20types_22',['MySQL supported types',['../d2/d0a/md_en_2userver_2mysql_2supported__types.html',1,'']]],
  ['switches_23',['Profiling context switches',['../db/d8f/md_en_2userver_2profile__context__switches.html',1,'']]],
  ['synchronization_20primitives_24',['Synchronization Primitives',['../d6/d6c/md_en_2userver_2synchronization.html',1,'']]],
  ['system_25',['Component system',['../dc/dcc/md_en_2userver_2component__system.html',1,'']]]
];
